require: rubocop-rspec

Metrics/LineLength:
  Max: 120 
Metrics/BlockLength:
  Enabled: false
Capybara/FeatureMethods:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
